# Site settings
title: EDGAR RODRÍGUEZ
description: 'Edgar Rodríguez'
url: 'https://codingedgar.com'
baseurl: ''
profilepic: '/images/favicons/android-chrome-512x512.png'
bkimage: '/images/pexels-kadri-vosumae-756903.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '80f7355090.js'

author:
  name: 'Edgar Rodríguez'
  email: codingedgar@gmail.com
  twitter_username: codingedgar
#  facebook_username: joshgerdes
  github_username:  codingedgar
  linkedin_username:  codingedgar
  instagram:  codingedgar
#  meetup_name: Azure-Meetup-Rostock-MV
  medium: '@codingedgar'
  youtube: https://www.youtube.com/channel/UCIrkqvbX0xx7Rm88kSGJ72Q
  new_youtube_video: https://youtu.be/siqhEc3QnxE
  new_blog_post: https://medium.com/javascript-in-plain-english/2-excellent-websites-for-web-developers-781339527ab0?source=friends_link&sk=15817e84345f0ed7060ace5d4ee68ba4
 
  
# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
